# Generated by Django 3.2.9 on 2022-01-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20220117_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernewuser',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
