# Generated by Django 3.2.9 on 2022-01-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_registernewuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registernewuser',
            options={},
        ),
    ]
