# Generated by Django 3.2.9 on 2022-01-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_registernewuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registernewuser',
            options={'ordering': ['id']},
        ),
    ]
