# Generated by Django 3.2.9 on 2022-01-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_registernewuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernewuser',
            name='username',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
