# Generated by Django 3.2.9 on 2022-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20220112_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='IMGSet1',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='IMGSet2',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='IMGSet3',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='IMGSet4',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
