# Generated by Django 3.2.9 on 2022-01-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_livingroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livingroom',
            options={'ordering': ['ProductID']},
        ),
    ]
